plot(df_set1$Xc,df_set1$Yc)
plot(df_set1$Xr,df_set1$Yr)
set1_p
plot(df_set2$Xc,df_set2$Yc)
plot(df_set2$Xr,df_set2$Yr)
set2_p
plot(df_set3$Xc,df_set3$Yc)
plot(df_set3$Xr,df_set3$Yr)
set3_p
plot(df_set4$Xc,df_set4$Yc)
plot(df_set4$Xr,df_set4$Yr)
set4_p
plot(df_set5$Xc,df_set5$Yc)
plot(df_set5$Xr,df_set5$Yr)
set5_p
plot(df_set6$Xc,df_set6$Yc)
plot(df_set6$Xr,df_set6$Yr)
set6_p
